baseURL = "https://latticesync.org/"
languageCode = "en-us"
title = "Lattice"
theme = "lattice-theme"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menus.main]]
    identifier = "reference"
    name = "Reference"
    weight = 90
  [[menus.main]]
    name = "Architecture"
    pageRef = "/architecture"
    parent = "reference"
    weight = 5
  [[menus.main]]
    name = "Simulation Harness"
    pageRef = "/simulation"
    parent = "reference"
    weight = 7
  [[menus.main]]
    name = "Roadmap"
    pageRef = "/roadmap"
    parent = "reference"
    weight = 10
